name: 'KiCad BOM'
description: 'Generates a BOM for a specified schematic and places them in a specified directory'
author: 'Emily McLean'
inputs:
  input-file:
    description: 'The PCB file to process'
    required: true
  output-file:
    description: 'The name of the resulting CSV BOM'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/emilymclean/kicad-bom:2.0.3'
  args:
    - ${{ inputs.input-file }}
    - ${{ inputs.output-file }}
branding:
  icon: 'cpu'
  color: 'green'